/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc;

import java.awt.Color;

/**
 *
 * @author vicen
 */
public class Calculator extends javax.swing.JFrame {
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        txtHistory.setEditable(false);
        txtNumberTemp.setEditable(false);
        button_Averange.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vista = new javax.swing.JPanel();
        button_Averange = new javax.swing.JTextField();
        ScrollNumber = new javax.swing.JScrollPane();
        txtNumberTemp = new javax.swing.JTextArea();
        txtHistory = new javax.swing.JTextField();
        button_Restart = new javax.swing.JButton();
        button_DEL = new javax.swing.JButton();
        button_Division = new javax.swing.JButton();
        button_Multiplication = new javax.swing.JButton();
        button_add = new javax.swing.JButton();
        button_Subtraction = new javax.swing.JButton();
        button_equal = new javax.swing.JButton();
        button_00 = new javax.swing.JButton();
        button_dot = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 255, 0));

        Vista.setBackground(new java.awt.Color(153, 255, 204));

        button_Averange.setBackground(new java.awt.Color(204, 204, 204));
        button_Averange.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_Averange.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNumberTemp.setColumns(20);
        txtNumberTemp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumberTemp.setRows(5);
        ScrollNumber.setViewportView(txtNumberTemp);

        txtHistory.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        button_Restart.setBackground(new Color(204, 204, 204));
        button_Restart.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        button_Restart.setText("AC");
        button_Restart.setToolTipText("");

        button_DEL.setBackground(new java.awt.Color(204, 204, 204));
        button_DEL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_DEL.setText("DEL");
        button_DEL.setToolTipText("");

        button_Division.setBackground(new java.awt.Color(204, 204, 204));
        button_Division.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_Division.setText("/");
        button_Division.setToolTipText("");

        button_Multiplication.setBackground(new java.awt.Color(204, 204, 204));
        button_Multiplication.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_Multiplication.setText("X");
        button_Multiplication.setToolTipText("");

        button_add.setBackground(new java.awt.Color(204, 204, 204));
        button_add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_add.setText("+");
        button_add.setToolTipText("");

        button_Subtraction.setBackground(new java.awt.Color(204, 204, 204));
        button_Subtraction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_Subtraction.setText("-");
        button_Subtraction.setToolTipText("");

        button_equal.setBackground(new java.awt.Color(204, 204, 204));
        button_equal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_equal.setText("=");
        button_equal.setToolTipText("");

        button_00.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_00.setText("00");
        button_00.setToolTipText("");

        button_dot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_dot.setText(".");
        button_dot.setToolTipText("");

        button_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_1.setText("1");
        button_1.setToolTipText("");

        button_3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_3.setText("3");
        button_3.setToolTipText("");

        button_4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_4.setText("4");
        button_4.setToolTipText("");

        button_6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_6.setText("6");
        button_6.setToolTipText("");

        button_7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_7.setText("7");
        button_7.setToolTipText("");

        button_9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_9.setText("9");
        button_9.setToolTipText("");

        button_0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_0.setText("0");
        button_0.setToolTipText("");

        button_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_2.setText("2");
        button_2.setToolTipText("");

        button_5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_5.setText("5");
        button_5.setToolTipText("");

        button_8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button_8.setText("8");
        button_8.setToolTipText("");

        javax.swing.GroupLayout VistaLayout = new javax.swing.GroupLayout(Vista);
        Vista.setLayout(VistaLayout);
        VistaLayout.setHorizontalGroup(
            VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHistory)
                    .addComponent(ScrollNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(VistaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VistaLayout.createSequentialGroup()
                                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(VistaLayout.createSequentialGroup()
                                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VistaLayout.createSequentialGroup()
                                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_Subtraction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VistaLayout.createSequentialGroup()
                                .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VistaLayout.createSequentialGroup()
                        .addComponent(button_Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Averange, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VistaLayout.createSequentialGroup()
                        .addComponent(button_00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VistaLayout.setVerticalGroup(
            VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_Averange, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(button_Restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_DEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VistaLayout.createSequentialGroup()
                        .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VistaLayout.createSequentialGroup()
                        .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(VistaLayout.createSequentialGroup()
                        .addComponent(button_Subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VistaLayout.createSequentialGroup()
                        .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollNumber;
    private javax.swing.JPanel Vista;
    public javax.swing.JButton button_0;
    public javax.swing.JButton button_00;
    public javax.swing.JButton button_1;
    public javax.swing.JButton button_2;
    public javax.swing.JButton button_3;
    public javax.swing.JButton button_4;
    public javax.swing.JButton button_5;
    public javax.swing.JButton button_6;
    public javax.swing.JButton button_7;
    public javax.swing.JButton button_8;
    public javax.swing.JButton button_9;
    private javax.swing.JTextField button_Averange;
    public javax.swing.JButton button_DEL;
    public javax.swing.JButton button_Division;
    public javax.swing.JButton button_Multiplication;
    public javax.swing.JButton button_Restart;
    public javax.swing.JButton button_Subtraction;
    public javax.swing.JButton button_add;
    public javax.swing.JButton button_dot;
    public javax.swing.JButton button_equal;
    public javax.swing.JTextField txtHistory;
    public javax.swing.JTextArea txtNumberTemp;
    // End of variables declaration//GEN-END:variables
}
